import Link from 'next/link'
import { ConsentBanner } from '@/components/ConsentBanner'
import { Container } from '@/components/Container'
import { faqs, services, site, zones } from '@/data/site'

const features = [
  ['01', 'Una risposta che parte dalla tua posizione', 'Quando il mezzo si ferma, raccogliamo subito dove ti trovi, quale veicolo deve essere recuperato e che cosa è successo.'],
  ['02', 'Il mezzo adatto alla situazione', 'Auto, moto, furgoni e veicoli incidentati richiedono attenzioni diverse. Consideriamo accesso, peso, danni e destinazione.'],
  ['03', 'Comunicazioni chiare fino alla consegna', 'Prima del recupero definiamo il prossimo passaggio e la destinazione concordata, così sai sempre come procede l’assistenza.'],
]

const gallery = [
  ['Soccorso senza confusione', 'Un contatto diretto per capire la situazione e organizzare il traino con ordine.', '/images/services/soccorso-stradale-24-ore.webp', 'border-orange-200 bg-orange-50'],
  ['Recupero dopo un imprevisto', 'Dalla panne all’incidente, valutiamo le condizioni del mezzo prima di muoverlo.', '/images/services/recupero-auto-incidentata.webp', 'border-sky-200 bg-sky-50'],
  ['Una destinazione concordata', 'Officina, carrozzeria, deposito o altro indirizzo: il veicolo viene portato dove serve.', '/images/services/trasporto-veicoli.webp', 'border-emerald-200 bg-emerald-50'],
]

const reviews = [
  ['“Sono rimasto fermo vicino alla circonvallazione. Mi hanno fatto le domande giuste e organizzato il recupero senza perdere tempo.”', 'Marco, Catania'],
  ['“Dopo un guasto non sapevo se fosse possibile spostare l’auto. Ho ricevuto indicazioni precise e una destinazione chiara.”', 'Elena, Acireale'],
  ['“Moto recuperata con attenzione. Comunicazione semplice dall’inizio alla consegna in officina.”', 'Davide, Misterbianco'],
]

function CallButton({ light = false, children = 'Chiama ora' }: { light?: boolean; children?: React.ReactNode }) {
  return <Link href={`tel:${site.tel}`} className={light ? 'inline-flex min-h-12 items-center justify-center rounded-full bg-white px-6 py-3 text-sm font-extrabold text-slate-950 shadow-lg transition hover:-translate-y-0.5' : 'inline-flex min-h-12 items-center justify-center rounded-full bg-orange-500 px-6 py-3 text-sm font-extrabold text-white shadow-lg shadow-orange-500/25 transition hover:-translate-y-0.5 hover:bg-orange-600'}>{children}<span className="ml-3 text-lg leading-none">→</span></Link>
}

export default function LogoIpsumCataniaHome() {
  return <div className="bg-[#fbfcfe] text-slate-950">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><Container className="flex min-h-[76px] items-center justify-between gap-6"><Link href="/" className="flex items-center gap-3"><img src="/logo.svg" alt={site.name} className="h-10 w-auto" /><span className="hidden text-sm font-black tracking-tight text-slate-950 sm:block">{site.name}</span></Link><nav className="hidden items-center gap-7 text-sm font-bold text-slate-600 lg:flex"><a href="#servizi" className="transition hover:text-slate-950">Servizi</a><a href="#come-funziona" className="transition hover:text-slate-950">Come funziona</a><a href="#zone" className="transition hover:text-slate-950">Zone servite</a><a href="#faq" className="transition hover:text-slate-950">FAQ</a></nav><CallButton>{site.phone}</CallButton></Container></header>
    <main>
      <section className="overflow-hidden border-b border-slate-200 bg-white"><Container className="grid gap-14 py-16 sm:py-24 lg:grid-cols-[1fr_0.9fr] lg:items-center lg:py-28"><div className="max-w-3xl"><p className="mb-6 text-xs font-black uppercase tracking-[0.24em] text-orange-600">Soccorso stradale attivo 24 ore</p><h1 className="text-5xl font-black leading-[0.98] tracking-[-0.07em] text-slate-950 sm:text-7xl lg:text-[6.6rem]">Carroattrezzi a Catania</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-slate-600 sm:text-xl">Quando auto, moto o furgone non possono più proseguire, trovi un riferimento concreto per organizzare il recupero in città e provincia. Ti aiutiamo a chiarire la situazione e a portare il veicolo dove serve.</p><div className="mt-9 flex flex-wrap items-center gap-4"><CallButton>Chiama {site.phone}</CallButton><Link href="#servizi" className="inline-flex min-h-12 items-center rounded-full border border-slate-300 px-6 py-3 text-sm font-extrabold text-slate-700 transition hover:border-slate-950 hover:text-slate-950">Scopri i servizi <span className="ml-3 text-lg">→</span></Link></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm font-bold text-slate-500"><span>24 ore su 24</span><span>•</span><span>Catania e provincia</span><span>•</span><span>Auto, moto e furgoni</span></div></div><div className="relative"><div className="absolute -inset-5 rounded-[2.5rem] bg-orange-100/70 blur-2xl" /><div className="relative overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-100 p-3 shadow-[0_30px_80px_rgba(15,23,42,.16)]"><img src="/images/home-hero.jpg" alt="Carroattrezzi pronto per un intervento a Catania" className="h-[360px] w-full rounded-[1.5rem] object-cover sm:h-[500px]" /><div className="absolute bottom-7 left-7 right-7 flex items-center justify-between rounded-2xl border border-white/50 bg-white/95 p-4 shadow-xl backdrop-blur"><div><p className="text-xs font-black uppercase tracking-widest text-orange-600">Richiesta assistenza</p><p className="mt-1 text-sm font-bold text-slate-900">Parliamo del tuo veicolo</p></div><Link href={`tel:${site.tel}`} aria-label="Chiama il soccorso stradale" className="grid h-12 w-12 place-items-center rounded-full bg-orange-500 text-xl font-black text-white">↗</Link></div></div></div></Container></section>
      <section id="come-funziona" className="bg-[#f4f7fb] py-20 sm:py-28"><Container><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-black uppercase tracking-[0.24em] text-orange-600">Un metodo semplice</p><h2 className="mt-4 text-4xl font-black tracking-[-0.06em] text-slate-950 sm:text-6xl">Dalla prima chiamata al recupero, sai sempre cosa succede.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Un percorso pratico per chi ha bisogno di assistenza: informazioni essenziali, mezzo adeguato e destinazione chiara.</p></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{features.map(([number, title, text]) => <article key={number} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><span className="text-4xl font-black tracking-[-0.08em] text-orange-500">{number}</span><h3 className="mt-8 text-xl font-black leading-tight text-slate-950">{title}</h3><p className="mt-4 text-base leading-7 text-slate-600">{text}</p></article>)}</div></Container></section>
      <section id="servizi" className="bg-white py-20 sm:py-28"><Container><div className="grid gap-8 lg:grid-cols-[0.75fr_1.25fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[0.24em] text-orange-600">Interventi disponibili</p><h2 className="mt-4 text-4xl font-black tracking-[-0.06em] text-slate-950 sm:text-6xl">La soluzione giusta per ogni fermo.</h2></div><p className="max-w-xl text-lg leading-8 text-slate-600 lg:justify-self-end">Ogni servizio viene valutato in base al mezzo, alla posizione e alla destinazione. Apri la scheda che descrive meglio ciò che ti è successo.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => <Link key={service.slug} href={`/servizi/${service.slug}/`} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white transition hover:-translate-y-1 hover:border-orange-300 hover:shadow-xl"><div className="h-48 overflow-hidden bg-slate-100"><img src={`/images/services/${service.slug}.webp`} alt={service.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-6"><div className="flex items-center justify-between"><span className="text-xs font-black text-orange-600">0{index + 1}</span><span className="text-slate-400 transition group-hover:translate-x-1">↗</span></div><h3 className="mt-5 text-xl font-black text-slate-950">{service.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{service.text}</p></div></Link>)}</div></Container></section>
      <section className="bg-slate-950 py-16 text-white sm:py-20"><Container><p className="text-center text-xs font-black uppercase tracking-[0.24em] text-orange-300">Un solo contatto, più possibilità di intervento</p><div className="mt-9 grid gap-8 text-center sm:grid-cols-3"><div><p className="text-4xl font-black text-white">24H</p><p className="mt-2 text-sm text-slate-300">Disponibilità per richieste urgenti</p></div><div><p className="text-4xl font-black text-white">Catania</p><p className="mt-2 text-sm text-slate-300">Città e comuni della provincia</p></div><div><p className="text-4xl font-black text-white">1 contatto</p><p className="mt-2 text-sm text-slate-300">Per traino, recupero e trasporto</p></div></div></Container></section>
      <section className="bg-[#f4f7fb] py-20 sm:py-28"><Container><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-black uppercase tracking-[0.24em] text-orange-600">Tre situazioni, una risposta ordinata</p><h2 className="mt-4 text-4xl font-black tracking-[-0.06em] text-slate-950 sm:text-6xl">Quando il mezzo non riparte, la priorità è rimettere ordine.</h2></div><div className="mt-14 grid gap-6 lg:grid-cols-3">{gallery.map(([title, text, image, color]) => <article key={title} className={`overflow-hidden rounded-3xl border ${color} shadow-sm`}><div className="h-56 overflow-hidden"><img src={image} alt={title} className="h-full w-full object-cover" /></div><div className="p-7"><h3 className="text-xl font-black text-slate-950">{title}</h3><p className="mt-3 text-base leading-7 text-slate-600">{text}</p></div></article>)}</div></Container></section>
      <section id="zone" className="bg-white py-20 sm:py-28"><Container><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[0.24em] text-orange-600">Presenza sul territorio</p><h2 className="mt-4 text-4xl font-black tracking-[-0.06em] text-slate-950 sm:text-6xl">Catania e i comuni vicini.</h2><p className="mt-6 max-w-md text-lg leading-8 text-slate-600">Puoi contattarci dal centro città, dalla zona costiera o dai comuni dell’area metropolitana. La pagina della tua località raccoglie indicazioni e servizi dedicati.</p></div><div className="grid gap-x-8 sm:grid-cols-2">{zones.map((zone) => <Link key={zone.slug} href={`/zone/${zone.slug}/`} className="flex items-center justify-between border-b border-slate-200 py-4 text-base font-extrabold text-slate-800 transition hover:border-orange-400 hover:text-orange-600"><span>{zone.name}</span><span className="text-slate-400">↗</span></Link>)}</div></div></Container></section>
      <section className="border-y border-slate-200 bg-[#f4f7fb] py-20 sm:py-28"><Container><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[0.24em] text-orange-600">Esperienze reali</p><h2 className="mt-4 text-4xl font-black tracking-[-0.06em] text-slate-950 sm:text-6xl">La tranquillità comincia da una risposta chiara.</h2></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{reviews.map(([quote, author]) => <blockquote key={author} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="text-lg tracking-[0.2em] text-orange-500">★★★★★</div><p className="mt-6 text-lg font-bold leading-8 text-slate-800">{quote}</p><footer className="mt-8 text-sm font-black text-slate-500">{author}</footer></blockquote>)}</div></Container></section>
      <section id="faq" className="bg-white py-20 sm:py-28"><Container className="max-w-4xl"><div className="text-center"><p className="text-xs font-black uppercase tracking-[0.24em] text-orange-600">Domande frequenti</p><h2 className="mt-4 text-4xl font-black tracking-[-0.06em] text-slate-950 sm:text-6xl">Prima di chiamare, ecco cosa sapere.</h2></div><div className="mt-12 divide-y divide-slate-200 border-y border-slate-200">{faqs.map((faq, index) => <details key={`${faq.question}-${index}`} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-lg font-black text-slate-950">{faq.question.replace(' a ', ` a ${site.city} `)}<span className="text-2xl font-normal text-orange-500 transition group-open:rotate-45">+</span></summary><p className="mt-4 max-w-3xl text-base leading-8 text-slate-600">{faq.answer}</p></details>)}</div></Container></section>
      <section className="bg-orange-500 py-20 text-white sm:py-28"><Container className="text-center"><p className="text-xs font-black uppercase tracking-[0.24em] text-orange-100">Il veicolo è fermo?</p><h2 className="mx-auto mt-4 max-w-4xl text-4xl font-black tracking-[-0.06em] sm:text-6xl">Parliamo adesso del recupero a Catania.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-orange-50">Una telefonata è il modo più semplice per descrivere la situazione e capire rapidamente quale intervento organizzare.</p><div className="mt-9"><CallButton light>Chiama {site.phone}</CallButton></div></Container></section>
    </main>
    <footer className="border-t border-slate-200 bg-white py-12"><Container className="grid gap-8 md:grid-cols-[1.2fr_0.8fr_0.8fr]"><div><div className="flex items-center gap-3"><img src="/logo.svg" alt={site.name} className="h-9 w-auto" /><strong className="text-sm text-slate-950">{site.name}</strong></div><p className="mt-5 max-w-sm text-sm leading-7 text-slate-500">Soccorso stradale, traino e recupero veicoli a Catania e provincia. Un riferimento concreto quando non puoi proseguire.</p></div><div><p className="text-xs font-black uppercase tracking-widest text-slate-400">Contatti</p><Link href={`tel:${site.tel}`} className="mt-4 block font-black text-slate-900">{site.phone}</Link><p className="mt-2 text-sm text-slate-500">{site.email}</p><p className="mt-2 text-sm leading-6 text-slate-500">{site.address}</p></div><div><p className="text-xs font-black uppercase tracking-widest text-slate-400">Navigazione</p><Link href="#servizi" className="mt-4 block text-sm font-bold text-slate-600">Servizi</Link><Link href="#zone" className="mt-2 block text-sm font-bold text-slate-600">Zone servite</Link><Link href="#faq" className="mt-2 block text-sm font-bold text-slate-600">FAQ</Link></div></Container><Container className="mt-10 border-t border-slate-200 pt-6 text-xs text-slate-400">© {new Date().getFullYear()} {site.name}. Tutti i diritti riservati.</Container></footer>
    <Link href={`tel:${site.tel}`} className="fixed bottom-4 right-4 z-40 rounded-full bg-orange-500 px-5 py-3 text-sm font-black text-white shadow-xl shadow-orange-500/30">Chiama</Link><ConsentBanner />
  </div>
}
